name: TeX Action

on: [workflow_dispatch]

jobs:
    tex-action:
        name: TeX the file
        runs-on: ubuntu-18.04
        defaults:
            run:
                working-directory: ./finish
        
        steps:
        
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Where am I
          run: pwd
          
        - name: Run TeX
          run: strace -o ./story.strace ./bin/pdftex story
          continue-on-error: true
          env: 
                TEXMFCNF: texlive/texmf-dist/web2c/
                TEXFORMATS: texlive/texmf-var/web2c/pdftex/ 
       
        - name: Upload PDF file
          uses: actions/upload-artifact@v2
          with:
            name: PDF
            path: ./finish/story.pdf
